-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 16:47:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventario` ;

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`rolusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`rolusuario` ;

CREATE TABLE IF NOT EXISTS `inventario`.`rolusuario` (
  `Id_Rol` INT NOT NULL,
  `Rol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`usuario` ;

CREATE TABLE IF NOT EXISTS `inventario`.`usuario` (
  `Id_Usuario` INT NOT NULL,
  `Id_Rol_Us` INT NOT NULL,
  `Nombre_Usuario` VARCHAR(100) NOT NULL,
  `Apellido_Usuario` VARCHAR(100) NOT NULL,
  `Correo_Usuario` VARCHAR(100) NOT NULL,
  `Usuario` VARCHAR(100) NOT NULL,
  `Clave_Usuario` VARCHAR(100) NOT NULL,
  `Estado_Usuario` INT NOT NULL DEFAULT '1',
  `Foto_Usuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Usuario`),
  INDEX `Rol-Usuario` (`Id_Rol_Us` ASC) VISIBLE,
  CONSTRAINT `Rol-Usuario`
    FOREIGN KEY (`Id_Rol_Us`)
    REFERENCES `inventario`.`rolusuario` (`Id_Rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`cliente` ;

CREATE TABLE IF NOT EXISTS `inventario`.`cliente` (
  `Id_Cliente` INT NOT NULL,
  `CI_Cliente` VARCHAR(100) NOT NULL,
  `Nombre_Cliente` VARCHAR(100) NOT NULL,
  `Apellido_Cliente` VARCHAR(100) NOT NULL,
  `Telefono_Cliente` VARCHAR(100) NOT NULL,
  `Direccion_Cliente` VARCHAR(100) NOT NULL,
  `Estado_Cliente` INT NOT NULL DEFAULT '1',
  `Dateadd_Cliente` DATETIME NOT NULL DEFAULT now(),
  `Id_Usuario` INT NOT NULL,
  PRIMARY KEY (`Id_Cliente`),
  INDEX `cliente_ibfk_1` (`Id_Usuario` ASC) VISIBLE,
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `inventario`.`usuario` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`configuracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`configuracion` ;

CREATE TABLE IF NOT EXISTS `inventario`.`configuracion` (
  `Id_Conf` INT NOT NULL,
  `CI_Conf` VARCHAR(20) NOT NULL,
  `Nombre_Conf` VARCHAR(100) NOT NULL,
  `RazonSocial_Conf` VARCHAR(100) NOT NULL,
  `Telefono_Conf` VARCHAR(20) NOT NULL,
  `Email_Conf` VARCHAR(20) NOT NULL,
  `Direccion_Conf` TEXT NOT NULL,
  `IVA_Conf` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`Id_Conf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`factura` ;

CREATE TABLE IF NOT EXISTS `inventario`.`factura` (
  `Id_Factura` INT NOT NULL,
  `Fecha_Factura` DATETIME NOT NULL DEFAULT now(),
  `Id_Usuario_Fac` INT NOT NULL,
  `Id_Cliente_Fac` INT NOT NULL,
  `Total_Fac` DECIMAL(10,2) NOT NULL,
  `Estado_Fac` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id_Factura`),
  INDEX `Factura-Cliente` (`Id_Cliente_Fac` ASC) VISIBLE,
  INDEX `Factura-Usuario` (`Id_Usuario_Fac` ASC) VISIBLE,
  CONSTRAINT `Factura-Cliente`
    FOREIGN KEY (`Id_Cliente_Fac`)
    REFERENCES `inventario`.`cliente` (`Id_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Factura-Usuario`
    FOREIGN KEY (`Id_Usuario_Fac`)
    REFERENCES `inventario`.`usuario` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `inventario`.`proveedores` (
  `Id_Proveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Proveedor` VARCHAR(100) NOT NULL,
  `Telefono_Proveedor` VARCHAR(15) NULL DEFAULT NULL,
  `Email_Proveedor` VARCHAR(100) NULL DEFAULT NULL,
  `Direccion_Proveedor` TEXT NULL DEFAULT NULL,
  `Estado_Proveedor` INT NULL DEFAULT '1',
  PRIMARY KEY (`Id_Proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`producto` ;

CREATE TABLE IF NOT EXISTS `inventario`.`producto` (
  `Id_Producto` INT NOT NULL,
  `Id_Usuario_Prod` INT NOT NULL,
  `Id_Proveedor` INT NULL DEFAULT NULL,
  `Desc_Producto` VARCHAR(50) NOT NULL,
  `Existencia_Prod` INT NOT NULL,
  `PrecioUnit_Prod` DECIMAL(10,2) NOT NULL,
  `Foto_Prod` TEXT NOT NULL,
  `dateadd_Prod` DATETIME NOT NULL DEFAULT now(),
  `Estado_Prod` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id_Producto`),
  INDEX `Producto_Proveedor` (`Id_Proveedor` ASC) VISIBLE,
  INDEX `Producto-Usuario` (`Id_Usuario_Prod` ASC) VISIBLE,
  CONSTRAINT `Producto-Usuario`
    FOREIGN KEY (`Id_Usuario_Prod`)
    REFERENCES `inventario`.`usuario` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Producto_Proveedor`
    FOREIGN KEY (`Id_Proveedor`)
    REFERENCES `inventario`.`proveedores` (`Id_Proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`factura_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`factura_detalle` ;

CREATE TABLE IF NOT EXISTS `inventario`.`factura_detalle` (
  `Id_Factura_Det` INT NOT NULL,
  `Id_Factura` INT NOT NULL,
  `Id_Producto_Fac_Det` INT NOT NULL,
  `Cantidad_Fac_Det` INT NOT NULL,
  `PrecioTotal_Fac_Det` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Id_Factura_Det`),
  INDEX `FacturaDet-Factura` (`Id_Factura` ASC) VISIBLE,
  INDEX `FacturaDet-Producto` (`Id_Producto_Fac_Det` ASC) VISIBLE,
  CONSTRAINT `FacturaDet-Factura`
    FOREIGN KEY (`Id_Factura`)
    REFERENCES `inventario`.`factura` (`Id_Factura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FacturaDet-Producto`
    FOREIGN KEY (`Id_Producto_Fac_Det`)
    REFERENCES `inventario`.`producto` (`Id_Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`factura_temp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`factura_temp` ;

CREATE TABLE IF NOT EXISTS `inventario`.`factura_temp` (
  `Id_Factura_Temp` INT NOT NULL,
  `Id_Factura_Temp_Usuario` INT NOT NULL,
  `Id_Factura_Temp_Prod` INT NOT NULL,
  `Cantidad_Factura_Temp` INT NOT NULL,
  `Precio_Venta_Temp` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Id_Factura_Temp`),
  INDEX `FacturaTemp-Producto` (`Id_Factura_Temp_Prod` ASC) VISIBLE,
  INDEX `FacturaTemp-Usuario` (`Id_Factura_Temp_Usuario` ASC) VISIBLE,
  CONSTRAINT `FacturaTemp-Producto`
    FOREIGN KEY (`Id_Factura_Temp_Prod`)
    REFERENCES `inventario`.`producto` (`Id_Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FacturaTemp-Usuario`
    FOREIGN KEY (`Id_Factura_Temp_Usuario`)
    REFERENCES `inventario`.`usuario` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`users` ;

CREATE TABLE IF NOT EXISTS `inventario`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`follows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`follows` ;

CREATE TABLE IF NOT EXISTS `inventario`.`follows` (
  `following_user_id` INT NULL DEFAULT NULL,
  `followed_user_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `following_user_id` (`following_user_id` ASC) VISIBLE,
  INDEX `followed_user_id` (`followed_user_id` ASC) VISIBLE,
  CONSTRAINT `follows_ibfk_1`
    FOREIGN KEY (`following_user_id`)
    REFERENCES `inventario`.`users` (`id`),
  CONSTRAINT `follows_ibfk_2`
    FOREIGN KEY (`followed_user_id`)
    REFERENCES `inventario`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`unidad` ;

CREATE TABLE IF NOT EXISTS `inventario`.`unidad` (
  `Id_Unidad` INT NOT NULL,
  `Nombre_Unidad` VARCHAR(11) NOT NULL,
  `Nombre_Unidades` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Id_Unidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`material` ;

CREATE TABLE IF NOT EXISTS `inventario`.`material` (
  `Id_Material` INT NOT NULL,
  `Id_Unidad` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Nombre_Material` VARCHAR(50) NOT NULL,
  `CostoPorUnidad_Material` FLOAT NOT NULL,
  `Existencia_Material` FLOAT NOT NULL,
  `Estado_Material` INT NOT NULL DEFAULT '1',
  `Dateadd_Material` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`Id_Material`),
  INDEX `Material-Unidad` (`Id_Unidad` ASC) VISIBLE,
  INDEX `Material-Usuario` (`Id_Usuario` ASC) VISIBLE,
  CONSTRAINT `Material-Unidad`
    FOREIGN KEY (`Id_Unidad`)
    REFERENCES `inventario`.`unidad` (`Id_Unidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Material-Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `inventario`.`usuario` (`Id_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`kardex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`kardex` ;

CREATE TABLE IF NOT EXISTS `inventario`.`kardex` (
  `Id_Kardex` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Id_Material` INT NOT NULL,
  `Fecha_K` DATETIME NOT NULL DEFAULT now(),
  `Desc_K` VARCHAR(100) NOT NULL,
  `Valor_Unit_K` FLOAT NOT NULL,
  `Cantidad_Ent_K` FLOAT NOT NULL,
  `Valor_Ent_K` FLOAT NOT NULL,
  `Cantidad_Sal_K` FLOAT NOT NULL,
  `Valor_Sal_K` FLOAT NOT NULL,
  `Cantidad_Saldo_k` FLOAT NOT NULL,
  `Valor_Saldo_K` FLOAT NOT NULL,
  PRIMARY KEY (`Id_Kardex`),
  INDEX `Kardex-Material` (`Id_Material` ASC) VISIBLE,
  INDEX `Kardex-Usuario` (`Id_Usuario` ASC) VISIBLE,
  CONSTRAINT `Kardex-Material`
    FOREIGN KEY (`Id_Material`)
    REFERENCES `inventario`.`material` (`Id_Material`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Kardex-Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `inventario`.`usuario` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`posts` ;

CREATE TABLE IF NOT EXISTS `inventario`.`posts` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `body` TEXT NULL DEFAULT NULL COMMENT 'Content of the post',
  `user_id` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `posts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inventario`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`producto_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`producto_detalle` ;

CREATE TABLE IF NOT EXISTS `inventario`.`producto_detalle` (
  `Id_Producto_Detalle` INT NOT NULL,
  `Id_Producto_Prod` INT NOT NULL,
  `Id_Material_Prod_Detalle` INT NOT NULL,
  `Existencia_Prod_Detalle` DECIMAL(10,2) NOT NULL,
  `PrecioUnit_Prod_Detalle` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Id_Producto_Detalle`),
  INDEX `Producto-Material-Detalle` (`Id_Material_Prod_Detalle` ASC) VISIBLE,
  INDEX `Producto-Producto` (`Id_Producto_Prod` ASC) VISIBLE,
  CONSTRAINT `Producto-Material-Detalle`
    FOREIGN KEY (`Id_Material_Prod_Detalle`)
    REFERENCES `inventario`.`material` (`Id_Material`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Producto-Producto`
    FOREIGN KEY (`Id_Producto_Prod`)
    REFERENCES `inventario`.`producto` (`Id_Producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventario`.`producto_temp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`producto_temp` ;

CREATE TABLE IF NOT EXISTS `inventario`.`producto_temp` (
  `Id_Producto_temp` INT NOT NULL,
  `Id_Material_Prod_temp` INT NOT NULL,
  `Id_Usuario_Prod_temp` INT NOT NULL,
  `Existencia_Prod_temp` INT NOT NULL,
  `PrecioUnit_Prod_temp` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Id_Producto_temp`),
  INDEX `Producto-Material-Temp` (`Id_Material_Prod_temp` ASC) VISIBLE,
  INDEX `Producto-Usuario-Temp` (`Id_Usuario_Prod_temp` ASC) VISIBLE,
  CONSTRAINT `Producto-Material-Temp`
    FOREIGN KEY (`Id_Material_Prod_temp`)
    REFERENCES `inventario`.`material` (`Id_Material`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Producto-Usuario-Temp`
    FOREIGN KEY (`Id_Usuario_Prod_temp`)
    REFERENCES `inventario`.`usuario` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
